### PR TITLE
fix error at by compile of determine OTP versions 20 or lower

### PR DESCRIPTION
**Pull request by Shpaky**

### CODE REVIEW

**Comment by Shpaky** [comment]
http://erlang.org/doc/reference_manual/macros.html

**Comment by tonyrog** [comment]
Looks like you are missing an -else branch ?

**Comment by Shpaky** [comment]
Yes, you are absolutely right!
I am sorry for mistake.

**Comment by Shpaky** [comment]
Absent branch an -else was added.
I am sorry for mistake.

**Pull request closed without merging**
